# Schema for the configuration files of the form_user_search module.
form_user_search.settings:
  type: config_object
  label: 'form_user_search settings'
  mapping:
    example:
      type: string
      label: 'Example'
